### ISSUE TITLE
Can't use as child of another node, causes huge offset

### ISSUE THREAD

**Issue by elvisish** [coelhucas/godot-line3d#1]
I've tried using the Line3D node as a child of another, but for some reason there's a big offset between then positioning of the start/end Position3D objects and the Line3D. I'm not entirely sure how to fix this, maybe a way of setting as top_level?

**Comment by coelhucas** [comment]
Hey! Could you share a print of what's happening exactly and maybe share a reproduction example? I tried to replicate from what you said but everything seemed to work just fine:
Tree | Editor
-- | --
![image](https://user-images.githubusercontent.com/28108272/193688509-00638587-e977-47a6-b3a5-585d1012bbe4.png) | ![image](https://user-images.githubusercontent.com/28108272/193688355-021a7047-e8e2-4004-883e-5ea91f84720a.png)

Parent line points from Position 1 to 2, child goes from Parent line to Position 3

Was my reproduction attempt right?

**Comment by elvisish** [comment]
It seems like you replicated it the same, I'm not entirely sure what was causing the offset, but thanks for trying!
